uploads = []

[[generated]]
id = "ATZdKaC7ZszJ7xsvrBkoH"
uri = "file://artifacts/grafly/assets/images/icon.png"
type = "image"
title = "grafly app icon"

[[generated]]
id = "hcRM3F1olz5O26hbV-qwI"
uri = "file://artifacts/grafly/assets/designs/banking_home.png"
type = "image"
title = "banking home"

[[generated]]
id = "CgArBD057GAwb1jRL6KXA"
uri = "file://artifacts/grafly/assets/designs/food_detail.png"
type = "image"
title = "food detail"

[[generated]]
id = "eeA_jiGxx3ak6LCerBhdj"
uri = "file://artifacts/grafly/assets/designs/fitness_dash.png"
type = "image"
title = "fitness dash"

[[generated]]
id = "NgnOqNuEXTzi751MYpSMN"
uri = "file://artifacts/grafly/assets/designs/music_player.png"
type = "image"
title = "music player"

[[generated]]
id = "b_rV2yWFdNGxzvhvbQTUV"
uri = "file://artifacts/grafly/assets/designs/social_sneaker.png"
type = "image"
title = "generated_image"

[[generated]]
id = "h-hR3VeJL1OZd7yP5rVDV"
uri = "file://artifacts/grafly/assets/designs/social_coffee.png"
type = "image"
title = "generated_image"

[[generated]]
id = "kBavcUKHYMl8vmYSakxum"
uri = "file://artifacts/grafly/assets/designs/social_quote.png"
type = "image"
title = "generated_image"

[[generated]]
id = "XnQs3Wj7tt6MmVa_vCYPL"
uri = "file://artifacts/grafly/assets/designs/social_travel.png"
type = "image"
title = "generated_image"

[[outputs]]
id = "cVKPm29rJUcyGWY9WyhUW"
uri = "file://grafly-clean.tar.gz"
type = "unspecified"
title = "grafly-clean.tar.gz (5.6 MB)"

[[outputs]]
id = "MlVK-F_L6MhiUj9P5VKdT"
uri = "file://.local/outputs/Game-Learn-Design.pdf"
type = "pdf"
title = "Game Learn Design.pdf"
