// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/grafly-icons/Compare.tsx": () => import("../components/mockups/grafly-icons/Compare.tsx")
};
